# Generated by Django 3.0 on 2020-09-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario_id',
            new_name='usuarioid',
        ),
    ]
