# Generated by Django 3.0 on 2020-09-14 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default=False, max_length=80),
        ),
        migrations.AddField(
            model_name='perfil',
            name='perfilUsuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfilUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default=False, max_length=80),
        ),
    ]
