# Generated by Django 3.0 on 2020-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='perfilUsuario_id',
            new_name='usuario_id',
        ),
        migrations.AddField(
            model_name='perfil',
            name='propietario',
            field=models.BooleanField(default=False),
        ),
    ]
