# Generated by Django 3.0 on 2020-09-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200916_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='propietario',
        ),
    ]
