# Generated by Django 3.0 on 2020-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200904_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuarioid',
            new_name='usuario_id',
        ),
    ]
