# Generated by Django 3.0 on 2020-10-03 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacion', '0004_auto_20200930_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lt', models.CharField(max_length=50)),
                ('lg', models.CharField(max_length=50)),
                ('publicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapaPublicacion', to='publicacion.Publicaciones')),
            ],
        ),
    ]
