# Generated by Django 3.0 on 2020-10-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacion',
            old_name='lg',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='lt',
            new_name='lng',
        ),
    ]
