# Generated by Django 3.0 on 2020-10-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_auto_20200930_1142'),
        ('mapas', '0002_auto_20201003_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='publicacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapaPublicacion', to='publicacion.Publicaciones'),
        ),
    ]
