# Generated by Django 3.0 on 2020-09-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.BooleanField(default=False)),
                ('cable', models.BooleanField(default=False)),
                ('luz', models.BooleanField(default=False)),
                ('telefono', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.BooleanField(default=False)),
                ('departamento', models.BooleanField(default=False)),
                ('duplex', models.BooleanField(default=False)),
                ('habitacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('publicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('ambientes', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('cochera', models.BooleanField(default=False)),
                ('patio', models.BooleanField(default=False)),
                ('mascotas', models.BooleanField(default=False)),
                ('niños', models.BooleanField(default=False)),
                ('superficie', models.CharField(max_length=50)),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Servicios')),
                ('tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.Tipo_Inmueble')),
            ],
        ),
    ]
