# Generated by Django 3.0 on 2020-09-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
