# Generated by Django 3.0 on 2020-09-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='Agua',
            new_name='agua',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Cable',
            new_name='cable',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Cloaca',
            new_name='cloaca',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Gas',
            new_name='gas',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Internet',
            new_name='internet',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Luz',
            new_name='luz',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Telefonia',
            new_name='telefono',
        ),
    ]
