# Generated by Django 3.0 on 2020-09-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacion',
            new_name='Publicaciones',
        ),
    ]
