# Generated by Django 3.0 on 2020-09-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_publicaciones_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonaInmueble', to='publicacion.Zona'),
        ),
    ]
