# Generated by Django 3.0 on 2020-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20200908_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='cable',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='cloaca',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='luz',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='telefono',
        ),
        migrations.AddField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
