# Generated by Django 3.0 on 2020-09-18 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacion', '0002_auto_20200917_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='usuario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPublicacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
