# Generated by Django 3.0 on 2020-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
    ]
