# Generated by Django 3.0 on 2020-09-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_auto_20200908_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='nombre',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='servicios',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='servicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miServicios', to='publicacion.Servicios'),
        ),
    ]
