# Generated by Django 3.0 on 2020-09-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_auto_20200908_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='servicios',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='servicios',
            field=models.ManyToManyField(related_name='miServicios', to='publicacion.Servicios'),
        ),
    ]
