# Generated by Django 3.0 on 2020-09-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_auto_20200908_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='publicaciones')),
                ('publicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgInmueble', to='publicacion.Publicaciones')),
            ],
        ),
    ]
