# Generated by Django 3.0 on 2020-09-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0006_imagenes_publicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes_publicaciones',
            name='publicacion',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagenes',
            field=models.ManyToManyField(related_name='misImagenes', to='publicacion.Imagenes_Publicaciones'),
        ),
    ]
