# Generated by Django 3.0 on 2020-09-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0007_auto_20200913_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones'),
        ),
        migrations.DeleteModel(
            name='Imagenes_Publicaciones',
        ),
    ]
