# Generated by Django 3.0 on 2020-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0008_auto_20200913_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='publicaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='imagenes',
            field=models.ManyToManyField(related_name='misImagenes', to='publicacion.Imagenes_Publicaciones'),
        ),
    ]
