# Generated by Django 3.0 on 2020-09-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0009_auto_20200913_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='imagenes',
        ),
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='publicaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgPublicacion', to='publicacion.Publicaciones'),
        ),
    ]
