# Generated by Django 3.0 on 2020-09-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0010_auto_20200913_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes_publicaciones',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='img2',
            field=models.ImageField(null=True, upload_to='publicaciones'),
        ),
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='img3',
            field=models.ImageField(null=True, upload_to='publicaciones'),
        ),
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='img4',
            field=models.ImageField(null=True, upload_to='publicaciones'),
        ),
        migrations.AddField(
            model_name='imagenes_publicaciones',
            name='img5',
            field=models.ImageField(null=True, upload_to='publicaciones'),
        ),
    ]
