# Generated by Django 3.0 on 2020-09-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0011_auto_20200914_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes_publicaciones',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='imagenes_publicaciones',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='imagenes_publicaciones',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='imagenes_publicaciones',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='imagenes_publicaciones',
            name='img5',
        ),
    ]
