# Generated by Django 3.0 on 2020-09-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0002_auto_20200920_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='objetoP',
        ),
    ]
